### PR TITLE
Adding transition styles for the navigation.

### PR DESCRIPTION
**Pull request by danielcgold**
Adding button transitions in the nav so it looks nicer when you move around between sections.

### CODE REVIEW

**Comment by ghost** [comment]
@danielcgold thanks for putting this together. Is there a demo you could link to showing the effect? I'm not sure what the [Hugo Creative theme](http://themes.gohugo.io/theme/creative/) is using for animations, but if it's not using [Waypoints](http://imakewebthings.com/waypoints/) that'd probably be the library to go with for triggering animations at a certain point during the scroll.

**Comment by danielcgold** [comment]
Sure, it looks like this now. It's a little less jumpy when scrolling from section to section.

**Comment by ghost** [comment]
@danielcgold nice! @y7kim can we get this merged?

**Comment by ghost** [comment]
🎉 😸

**Pull request merged**
